documentation: add comments for empty commit scenario

diff --git a/git/hooks/pre-commit b/git/hooks/pre-commit
--- a/git/hooks/pre-commit
+++ b/git/hooks/pre-commit
@@ -228,7 +228,7 @@ if [ ${#files[@]} -eq 0 ]; then
   # this will also fail empty commits
   # if you wish to commit an empty commit
   # use the --no-verify option which will skip thie pre-commit
-  echo 1>&2 "No files changed after processing..."
+  echo 1>&2 "No files changed after processing or empty commit. Commit failed."
   ret=$((ret + 1))
 fi
 
