refactor: refactor binary scripts

diff --git a/binaries/checksql b/binaries/checksql
--- a/binaries/checksql
+++ b/binaries/checksql
@@ -1,13 +1,19 @@
-#!/usr/bin/env bash
+#!/usr/bin/env -e bash
+
 function require() {
-	hash "$@" || exit 127
+  hash "$@" || exit 127
 }
+
 require rm sqlcheck tee
+
 declare -i exitCode=0
-rm ./check.errors
+
+rm ./check.errors || { echo "Error removing check.errors"; exit 1; }
+
 for f in *.sql; do
-	test -e "$f" || continue
-	sqlcheck -c -v -f "$f" | tee -a check.errors
-	exitCode="$exitCode"+"$?"
+  [[ -e "$f" ]] || continue
+  sqlcheck -c -v -f "$f" | tee -a check.errors
+  (( exitCode |= $? ))
 done
+
 exit "$exitCode"
diff --git a/binaries/cleanuplogs b/binaries/cleanuplogs
--- a/binaries/cleanuplogs
+++ b/binaries/cleanuplogs
@@ -1,69 +1,75 @@
-#!/usr/bin/env bash
+#!/usr/bin/env -e bash
+
 # Cleanup, version 3
 
-#  Warning:
-#  -------
-#  This script uses quite a number of features that will be explained
-#+ later on.
-#  By the time you've finished the first half of the book,
-#+ there should be nothing mysterious about it.
-#
 function require() {
-	hash "$@" | exit 127
+  hash "$@" || exit 127
 }
+
 require mv tail dirname readlink basename
+
 MY_DIR="$(dirname "$(readlink -f "$0")")"
+
 # shellcheck disable=SC1091
 source "${MY_DIR}/debug.sh"
+
 # shellcheck disable=SC2034
 DEBUG=false
+
 # shellcheck disable=SC1091
 source "${MY_DIR}/debugon.sh"
+
 LOG_DIR="${PREFIX}/var/log"
+
 # Only users with $UID 0 have root privileges.
 ROOT_UID=0
+
 # Default number of lines saved.
 LINES=50
+
 # Can't change directory?
 E_XCD=86
+
 # Non-root exit error.
 E_NOTROOT=87
 
 # Run as root, of course.
-if [ "$UID" -ne "$ROOT_UID" ]; then
-	echo "Must be root to run this script."
-	exit "$E_NOTROOT"
+if (( UID != ROOT_UID )); then
+  printf "Must be root to run this script.\n" >&2
+  exit "$E_NOTROOT"
 fi
 
 # Non-numerical argument (bad argument format).
 E_WRONGARGS=85
 
 case "$1" in
-"")
-	lines=50
-	;;
-*[!0-9]*)
-	echo "Usage: $(basename "$0") lines-to-cleanup"
-	exit "$E_WRONGARGS"
-	;;
-*)
-	lines="$1"
-	;;
+  "")
+    lines=50
+    ;;
+  *[!0-9]*)
+    printf "Usage: %s lines-to-cleanup\n" "$(basename "$0")" >&2
+    exit "$E_WRONGARGS"
+    ;;
+  *)
+    lines="$1"
+    ;;
 esac
 
 cd "$LOG_DIR" || {
-	echo "Cannot change to necessary directory." >&2
-	exit "$E_XCD"
+  printf "Cannot change to necessary directory.\n" >&2
+  exit "$E_XCD"
 }
 
 # Save last section of pacman log file.
-tail -n "$lines" pacman.log >pacman.temp
-# Rename it as log file.
-mv pacman.temp pacman.log
+tail -n "$lines" pacman.log >pacman.temp &&
+  mv pacman.temp pacman.log
 
-#  ': > wtmp' and '> wtmp' have the same effect.
-cat /dev/null >wtmp
-echo "Log files cleaned up."
+# ': > wtmp' and '> wtmp' have the same effect.
+> wtmp
+
+printf "Log files cleaned up.\n"
+
 # shellcheck disable=SC1091
 source "${MY_DIR}/debugoff.sh"
+
 exit 0
