refactor: refactor binary scripts

diff --git a/binaries/checksql b/binaries/checksql
--- a/binaries/checksql
+++ b/binaries/checksql
@@ -1,19 +1,23 @@
-#!/usr/bin/env -e bash
+#!/usr/bin/env bash
 
 function require() {
   hash "$@" || exit 127
 }
 
+set -e
 require rm sqlcheck tee
 
 declare -i exitCode=0
 
-rm ./check.errors || { echo "Error removing check.errors"; exit 1; }
+rm ./check.errors || {
+  echo "Error removing check.errors"
+  exit 1
+}
 
 for f in *.sql; do
   [[ -e "$f" ]] || continue
   sqlcheck -c -v -f "$f" | tee -a check.errors
-  (( exitCode |= $? ))
+  ((exitCode |= $?))
 done
 
 exit "$exitCode"
diff --git a/binaries/gitadd b/binaries/gitadd
--- a/binaries/gitadd
+++ b/binaries/gitadd
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+
 ######################################################################
 # @author      : Linus Fernandes (linusfernandes@gmail.com)
 # @file        : gitadd
@@ -6,14 +7,23 @@
 # @copyright   : Copyright (c) Linus Fernandes
 # @description :
 ######################################################################
+
 function require() {
   hash "$@" || exit 127
 }
+
+set -e
 # shellcheck source=/dev/null
 source "${HOME}/.gitrc"
+
 require git hub
-command="git add ."
-eval "$command"
-command="git status"
-eval "$command"
+
+command=("git" "add" ".")
+if ! "${command[@]}"; then
+  echo "Error adding files to Git staging area" >&2
+  exit 1
+fi
+
+command=("git" "status")
+"${command[@]}"
 exit $?
