chore: format shell scripts

diff --git a/binaries/cleanuplogs b/binaries/cleanuplogs
--- a/binaries/cleanuplogs
+++ b/binaries/cleanuplogs
@@ -9,9 +9,9 @@
 #+ there should be nothing mysterious about it.
 #
 function require() {
-hash "$@" | exit 127;
+	hash "$@" | exit 127
 }
-require mv tail dirname readlink basename 
+require mv tail dirname readlink basename
 MY_DIR="$(dirname "$(readlink -f "$0")")"
 # shellcheck disable=SC1091
 source "${MY_DIR}/debug.sh"
@@ -21,49 +21,48 @@ DEBUG=false
 source "${MY_DIR}/debugon.sh"
 LOG_DIR="${PREFIX}/var/log"
 # Only users with $UID 0 have root privileges.
-ROOT_UID=0    
+ROOT_UID=0
 # Default number of lines saved.
-LINES=50       
+LINES=50
 # Can't change directory?
-E_XCD=86       
+E_XCD=86
 # Non-root exit error.
-E_NOTROOT=87   
+E_NOTROOT=87
 
 # Run as root, of course.
-if [ "$UID" -ne "$ROOT_UID" ]
-then
-  echo "Must be root to run this script."
-  exit "$E_NOTROOT"
-fi  
+if [ "$UID" -ne "$ROOT_UID" ]; then
+	echo "Must be root to run this script."
+	exit "$E_NOTROOT"
+fi
 
 # Non-numerical argument (bad argument format).
-E_WRONGARGS=85  
+E_WRONGARGS=85
 
 case "$1" in
-""      ) 
-  lines=50
-  ;;
-*[!0-9]*) 
-  echo "Usage: $(basename "$0") lines-to-cleanup";
-  exit "$E_WRONGARGS"
-  ;;
-*       ) 
-  lines="$1"
-  ;;
+"")
+	lines=50
+	;;
+*[!0-9]*)
+	echo "Usage: $(basename "$0") lines-to-cleanup"
+	exit "$E_WRONGARGS"
+	;;
+*)
+	lines="$1"
+	;;
 esac
 
 cd "$LOG_DIR" || {
-  echo "Cannot change to necessary directory." >&2
-  exit "$E_XCD";
+	echo "Cannot change to necessary directory." >&2
+	exit "$E_XCD"
 }
 
 # Save last section of pacman log file.
-tail -n "$lines" pacman.log > pacman.temp
+tail -n "$lines" pacman.log >pacman.temp
 # Rename it as log file.
-mv pacman.temp pacman.log               
+mv pacman.temp pacman.log
 
 #  ': > wtmp' and '> wtmp' have the same effect.
-cat /dev/null > wtmp  
+cat /dev/null >wtmp
 echo "Log files cleaned up."
 # shellcheck disable=SC1091
 source "${MY_DIR}/debugoff.sh"
diff --git a/binaries/unpack b/binaries/unpack
--- a/binaries/unpack
+++ b/binaries/unpack
@@ -3,40 +3,42 @@
 
 # Display usage if no parameters given
 if [[ -z "$*" ]]; then
-  echo " ${0##*/} <archive(s)> - extract common file formats)"
-    exit
+	echo " ${0##*/} <archive(s)> - extract common file formats)"
+	exit
 fi
 
 # Required program(s)
 # require functionality
 req_progs=(7z unrar unzip tar bunzip2 ar gunzip uncompress)
 for p in "${req_progs[@]}"; do
-    hash "$p" 2>&- || \
-    { echo >&2 " Required program \"$p\" not installed."; exit 1; }
+	hash "$p" 2>&- ||
+		{
+			echo >&2 " Required program \"$p\" not installed."
+			exit 1
+		}
 done
 
-for f in "$@"
-do
-  # Test if file exists
-  if [ ! -f "$f" ]; then
-    echo "File $f doesn't exist"
-    continue
-  fi
-  # Extract file by using extension as reference
-  case "$f" in
-      *.7z ) 7z x "$@" ;;
-      *.tar.bz2 ) tar xvjf "$@" ;;
-      *.bz2 ) bunzip2 "$@" ;;
-      *.deb ) ar vx "$@" ;;
-      *.tar.gz ) tar xvf "$@" ;;
-      *.gz ) gunzip "$@" ;;
-      *.tar ) tar xvf "$@" ;;
-      *.tbz2 ) tar xvjf "$@" ;;
-      *.tar.xz ) tar xvf "$@" ;;
-      *.tgz ) tar xvzf "$@" ;;
-      *.rar ) unrar x "$@" ;;
-      *.zip ) unzip "$@" ;;
-      *.Z ) uncompress "$@" ;;
-      * ) echo " Unsupported file format" ;;
-    esac
+for f in "$@"; do
+	# Test if file exists
+	if [ ! -f "$f" ]; then
+		echo "File $f doesn't exist"
+		continue
+	fi
+	# Extract file by using extension as reference
+	case "$f" in
+	*.7z) 7z x "$@" ;;
+	*.tar.bz2) tar xvjf "$@" ;;
+	*.bz2) bunzip2 "$@" ;;
+	*.deb) ar vx "$@" ;;
+	*.tar.gz) tar xvf "$@" ;;
+	*.gz) gunzip "$@" ;;
+	*.tar) tar xvf "$@" ;;
+	*.tbz2) tar xvjf "$@" ;;
+	*.tar.xz) tar xvf "$@" ;;
+	*.tgz) tar xvzf "$@" ;;
+	*.rar) unrar x "$@" ;;
+	*.zip) unzip "$@" ;;
+	*.Z) uncompress "$@" ;;
+	*) echo " Unsupported file format" ;;
+	esac
 done
