refactor: refactor binary scripts

diff --git a/binaries/gitalias b/binaries/gitalias
--- a/binaries/gitalias
+++ b/binaries/gitalias
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+
 ######################################################################
 # @author      : Linus Fernandes (linusfernandes@gmail.com)
 # @file        : gitalias
@@ -6,10 +7,16 @@
 # @copyright   : Copyright (c) Linus Fernandes
 # @description :
 ######################################################################
+
 require() {
   hash "$@" || exit
 }
+set -e
 require git
-command="git config --get-regexp ^alias\."
-eval "$command"
-exit $?
+
+if ! output=$(git config --get-regexp '^alias\.'); then
+  echo "Error retrieving Git aliases" >&2
+  exit 1
+fi
+
+printf "%s\n" "$output"
