refactor: refactor binary scripts

diff --git a/binaries/gitcommit b/binaries/gitcommit
--- a/binaries/gitcommit
+++ b/binaries/gitcommit
@@ -6,12 +6,24 @@
 # @copyright   : Copyright (c) Linus Fernandes
 # @description :
 ######################################################################
+
 require() {
   hash "$@" || exit
 }
+set -e
 require git hub
+
 # shellcheck source=/dev/null
 source "${HOME}/.gitrc"
-command="git commit -F commit.txt"
-eval "$command"
-exit $?
+
+if [[ ! -e commit.txt ]]; then
+  echo "Error: commit.txt not found" >&2
+  exit 1
+fi
+
+if ! git commit -F commit.txt; then
+  echo "Error committing changes" >&2
+  exit 1
+fi
+
+exit 0
