refactor: refactor binary scripts

diff --git a/binaries/gitdir b/binaries/gitdir
--- a/binaries/gitdir
+++ b/binaries/gitdir
@@ -1,6 +1,14 @@
 #!/usr/bin/env bash
+
 require() {
   hash "$@" || exit
 }
+
 require git readlink
-readlink -f "$(git rev-parse --git-dir)"
+
+if ! git_dir=$(readlink -f "$(git rev-parse --git-dir)"); then
+  echo "Error retrieving Git repository directory" >&2
+  exit 1
+fi
+
+printf "%s\n" "$git_dir"
