refactor: refactor binary scripts

diff --git a/binaries/gitfindcommit b/binaries/gitfindcommit
--- a/binaries/gitfindcommit
+++ b/binaries/gitfindcommit
@@ -1,11 +1,19 @@
 #!/usr/bin/env bash
+
 require() {
   hash "$@" || exit
 }
+set -e
 require git
-if [ $# -lt 1 ]; then
-  echo "usage: $0 searchstring"
+
+if [[ $# -lt 1 ]]; then
+  printf "usage: %s searchstring\n" "$0"
   exit 1
 fi
-git log --all --grep="$1"
-exit "$?"
+
+if ! git log --all --grep="$1"; then
+  printf "Error searching Git log\n" >&2
+  exit 1
+fi
+
+exit 0
