refactor: refactor binary scripts

diff --git a/binaries/gitlastcommit b/binaries/gitlastcommit
--- a/binaries/gitlastcommit
+++ b/binaries/gitlastcommit
@@ -6,10 +6,16 @@
 # @copyright   : Copyright (c) Linus Fernandes
 # @description :
 ######################################################################
+
 require() {
   hash "$@" || exit
 }
+set -e
 require git
-command="git log -n 1"
-eval "$command"
-exit $?
+
+if ! output=$(git log -n 1); then
+  echo "Error retrieving last Git commit" >&2
+  exit 1
+fi
+
+printf "%s\n" "$output"
