refactor: refactor binary scripts

diff --git a/binaries/gitmerged b/binaries/gitmerged
--- a/binaries/gitmerged
+++ b/binaries/gitmerged
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+
 ######################################################################
 # @author      : Linus Fernandes (linusfernandes@gmail.com)
 # @file        : gitpush
@@ -6,18 +7,17 @@
 # @copyright   : Copyright (c) Linus Fernandes
 # @description :
 ######################################################################
+
 RED="\033[0;31m"
 NC="\033[0m" # No Color
 
 function message() {
-  ret=$?
-  if [ "$ret" -eq 0 ]; then
-    echo "exit $ret from last command: $command"
+  local ret=$?
+  if ((ret == 0)); then
     git diff development main
     git gc
   else
-    echo "${RED}exit $ret from last command: $command${NC}"
-    echo "${RED}returning to branch development"
+    printf "%sReturning to branch development%s\n" "$RED" "$NC"
     git checkout development
   fi
   exit "$ret"
@@ -26,18 +26,30 @@ function message() {
 require() {
   hash "$@" || exit
 }
-require git
+
 set -e
-command=""
-trap message EXIT
+require git
 
 mainBranch="main"
 
-command="git checkout ${mainBranch}"
-eval "$command"
-command="git merge development"
-eval "$command"
-command="git push -u origin ${mainBranch}"
-eval "$command"
-command="git checkout development"
-eval "$command"
+trap message EXIT
+
+if ! git checkout "$mainBranch"; then
+  echo "Error checking out $mainBranch" >&2
+  exit 1
+fi
+
+if ! git merge development; then
+  echo "Error merging development into $mainBranch" >&2
+  exit 1
+fi
+
+if ! git push -u origin "$mainBranch"; then
+  echo "Error pushing changes to $mainBranch" >&2
+  exit 1
+fi
+
+if ! git checkout development; then
+  echo "Error checking out development" >&2
+  exit 1
+fi
