refactor: refactor binary scripts

diff --git a/binaries/lswoexts b/binaries/lswoexts
--- a/binaries/lswoexts
+++ b/binaries/lswoexts
@@ -1,3 +1,7 @@
 #!/usr/bin/env bash
-# shellcheck disable=SC2010
-ls -l -I '*.*' | grep -v '^d' | awk '{if ($9) print $9}'
+hash find &> /dev/null || {
+  echo "find not found. Kindly install it." >&2
+  exit 127
+}
+
+find . -maxdepth 1 -type f ! -name '*.*' -printf '%f\n'
